# Generated by Django 5.2.8 on 2025-12-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_flatno', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='raiseproblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.signup')),
            ],
        ),
        migrations.CreateModel(
            name='givesuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('approval', models.IntegerField(default=0)),
                ('reject', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.signup')),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_count', models.IntegerField(default=0)),
                ('reject_count', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.givesuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approval', models.BooleanField(default=False)),
                ('memberdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.signup')),
                ('suggestiondata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.givesuggestion')),
            ],
            options={
                'unique_together': {('memberdata', 'suggestiondata')},
            },
        ),
    ]
